### ISSUE TITLE
Running program without arguments leads to panic

### ISSUE THREAD

**Issue by littleli** [kordamp/gm#11]
I dislike the fact that commands panic when run without the arguments. It's unacceptable.

```
> gum.exe
panic: value method github.com/kordamp/gm/gum.MavenCommand.Execute called using nil *MavenCommand pointer

goroutine 1 [running]:
github.com/kordamp/gm/gum.(*MavenCommand).Execute(0x0)
        <autogenerated>:1 +0xb0
main.main()
        /home/runner/work/gm/gm/src/github.com/kordamp/gm/gm.go:56 +0x27f
```

Something like, use -gh for help or print help directly with different than 0 exit code is still better.

**Comment by manikmagar** [comment]
I am getting it even when I run `gm verify` on new installation - 

<img width="1127" alt="image" src="https://user-images.githubusercontent.com/877286/83977252-21f9c300-a8cd-11ea-804a-fef52c6b3361.png">

**Comment by aalmiray** [comment]
This happens *only* when invoking `gm` outside of a project directory.
