### ISSUE TITLE
Suggestion: use `gum` instead of `gm`

### ISSUE THREAD

**Issue by littleli** [kordamp/gm#12]
Why would I suggest that? Reason is quite simple. On Windows with Powershell, ie. all current versions of Windows `gm` is something else.  It's `Get-Members` command.

Technically  user can use `gm.exe` explicitly which resolves the problem, but it's a quite weird. As far as I know `gum` or `gum.exe` does not conflict with anything common.

Note: I'm working on scoop package manifest and I use scoop shim which is a workaroudn for this. Unpleasant fact of this solution is, that on Windows shim is not your program directly but intermediary binary.

**Comment by manikmagar** [comment]
Oh, and when using Oh-My-Zsh git aliases, it conflicted with `gm` alias for `git merge` -

<img width="1117" alt="image" src="https://user-images.githubusercontent.com/877286/83977201-ac8df280-a8cc-11ea-865d-f51208b93402.png">

**Comment by aalmiray** [comment]
I'd have to give this more thought. On one side the project is young so a rename is still possible without causing so much disruption. However I like `gm` and it does not conflict in other platforms as far as I'm aware.

Note that the official name of the project is "Gum" and that the snapcraft page also uses "gum" as the app name `gm` was reserved and I couldn't use it.

What about this, producing both `gm.exe` and `gum.exe` and let consumers decide which one they want to use?

**Comment by littleli** [comment]
@aalmiray There is a [PR](https://github.com/ScoopInstaller/Main/pull/1156) in a review that I submitted for Scoop package manager. You can check my solution there.

**Comment by aalmiray** [comment]
@littleli Great! FWIW goreleaser allows setting up scoop -> https://goreleaser.com/customization/scoop/

**Comment by littleli** [comment]
You can decide to go with your own bucket. In my opinion it limits a bit user experience, because user have to manipulate buckets before use. After checking source code of goreleaser, it does not support shims yet, so user will still face the naming issue above.

**Comment by aalmiray** [comment]
@littleli Got it. If gum can be added to main Scoop then the better. I'm thinking in releasing `0.4.0` this weekend.

**Comment by littleli** [comment]
@aalmiray PR with scoop package was [merged](https://github.com/ScoopInstaller/Main/pull/1156).

**Comment by aalmiray** [comment]
Awesome! Thank you 😄
