### ISSUE TITLE
Add support for jbang

### ISSUE THREAD

**Issue by aalmiray** [kordamp/gm#18]
https://github.com/jbangdev/jbang lets you launch Java/Jshell sources. It also sports a local wrapper.

Suggested by @shelajev.
Keeping @maxandersen happy 😄

**Comment by aalmiray** [comment]
Ping @maxandersen!

Usage: `gm <source> <args>` where source may be: URL (http*), a .java, or a .jsh file. If no explicit source is given then the first .java file is taken, otherwise the first .jsh

**Comment by maxandersen** [comment]
niice! :) how do you get jbang - just assume its in the path?

**Comment by aalmiray** [comment]
Yes, it's either on the path or the current dir has the jbang wrapper.
